"""deleting column

Revision ID: 1cefc6d03d9e
Revises: 53378b3394de
Create Date: 2026-05-03 16:12:08.183576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cefc6d03d9e'
down_revision: Union[str, Sequence[str], None] = '53378b3394de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'organization')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
