"""add org column

Revision ID: 53378b3394de
Revises: a34dbbc08939
Create Date: 2026-05-03 16:10:54.414696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53378b3394de'
down_revision: Union[str, Sequence[str], None] = 'a34dbbc08939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('organization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'organization')
    # ### end Alembic commands ###
