"""start docker

Revision ID: a34dbbc08939
Revises: 80f0912b205a
Create Date: 2026-05-03 16:09:10.753400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34dbbc08939'
down_revision: Union[str, Sequence[str], None] = '80f0912b205a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expertise', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_table('mentors')
    # ### end Alembic commands ###
