"""regenerate table

Revision ID: 0b626a181357
Revises: 9486385c2f93
Create Date: 2026-05-11 13:09:30.512528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b626a181357'
down_revision: Union[str, Sequence[str], None] = '9486385c2f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('added_by', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('resources_added__fkey'), 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'mentors', ['added_by'], ['id'])
    op.drop_column('resources', 'added_')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('added_', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key(op.f('resources_added__fkey'), 'resources', 'mentors', ['added_'], ['id'])
    op.drop_column('resources', 'added_by')
    # ### end Alembic commands ###
