"""test

Revision ID: 3d1162acbb6a
Revises: e7a13c363ae0
Create Date: 2026-05-08 18:39:58.759769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1162acbb6a'
down_revision: Union[str, Sequence[str], None] = 'e7a13c363ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_contacts', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergency_contacts', 'date')
    # ### end Alembic commands ###
