"""remove post foregn key

Revision ID: 4128348611b0
Revises: 4e0178abc216
Create Date: 2026-05-28 17:14:22.812539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4128348611b0'
down_revision: Union[str, Sequence[str], None] = '4e0178abc216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_author_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'migrants', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_author_id_fkey'), 'posts', 'mentors', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
