"""added rules

Revision ID: 71177ae37956
Revises: 0b626a181357
Create Date: 2026-05-23 11:06:32.848666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71177ae37956'
down_revision: Union[str, Sequence[str], None] = '0b626a181357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mentors_user_id_fkey'), 'mentors', type_='foreignkey')
    op.create_foreign_key(None, 'mentors', 'migrants', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.create_foreign_key(op.f('mentors_user_id_fkey'), 'mentors', 'migrants', ['user_id'], ['id'])
    # ### end Alembic commands ###
