"""mentor should depend

Revision ID: 7e87856b1603
Revises: ee5d9878344a
Create Date: 2026-05-10 09:58:30.790670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e87856b1603'
down_revision: Union[str, Sequence[str], None] = 'ee5d9878344a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('mentors_email_key'), 'mentors', type_='unique')
    op.drop_constraint(op.f('mentors_user_name_key'), 'mentors', type_='unique')
    op.create_foreign_key(None, 'mentors', 'migrants', ['user_id'], ['id'])
    op.drop_column('mentors', 'name')
    op.drop_column('mentors', 'native_country')
    op.drop_column('mentors', 'current_country')
    op.drop_column('mentors', 'password_hash')
    op.drop_column('mentors', 'created_at')
    op.drop_column('mentors', 'email')
    op.drop_column('mentors', 'role')
    op.drop_column('mentors', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mentors', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mentors', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mentors', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('mentors', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mentors', sa.Column('current_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mentors', sa.Column('native_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mentors', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.create_unique_constraint(op.f('mentors_user_name_key'), 'mentors', ['user_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('mentors_email_key'), 'mentors', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('mentors', 'user_id')
    # ### end Alembic commands ###
