"""adding otp_verfied

Revision ID: 84357b44b7b4
Revises: fce910841689
Create Date: 2026-06-07 10:17:01.699439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84357b44b7b4'
down_revision: Union[str, Sequence[str], None] = 'fce910841689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migrants', sa.Column('is_otp_verified', sa.Boolean(), nullable=False ,server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migrants', 'is_otp_verified')
    # ### end Alembic commands ###
