"""added org column to mentor

Revision ID: 9486385c2f93
Revises: 7e87856b1603
Create Date: 2026-05-10 10:16:23.737569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9486385c2f93'
down_revision: Union[str, Sequence[str], None] = '7e87856b1603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('organization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'organization')
    # ### end Alembic commands ###
