"""added rules to resource and post

Revision ID: db407631013e
Revises: 71177ae37956
Create Date: 2026-05-23 11:14:03.049742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db407631013e'
down_revision: Union[str, Sequence[str], None] = '71177ae37956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_author_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'mentors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resources_added_by_fkey'), 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'mentors', ['added_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key(op.f('resources_added_by_fkey'), 'resources', 'mentors', ['added_by'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_author_id_fkey'), 'posts', 'mentors', ['author_id'], ['id'])
    # ### end Alembic commands ###
