"""added date and time

Revision ID: e1e773fc121e
Revises: 0b626a181357
Create Date: 2026-05-24 10:03:05.043243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e773fc121e'
down_revision: Union[str, Sequence[str], None] = '0b626a181357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emergency_contacts', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="date::timestamp with time zone",
               existing_nullable=True)
               
    op.drop_constraint(op.f('mentors_user_id_fkey'), 'mentors', type_='foreignkey')
    op.create_foreign_key(None, 'mentors', 'migrants', ['user_id'], ['id'])
    op.drop_constraint(op.f('posts_author_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'mentors', ['author_id'], ['id'])
    op.drop_constraint(op.f('resources_added_by_fkey'), 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'mentors', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key(op.f('resources_added_by_fkey'), 'resources', 'mentors', ['added_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_author_id_fkey'), 'posts', 'mentors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.create_foreign_key(op.f('mentors_user_id_fkey'), 'mentors', 'migrants', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('emergency_contacts', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
