"""adding column

Revision ID: ee5d9878344a
Revises: f348ffc126ac
Create Date: 2026-05-08 20:54:43.637164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5d9878344a'
down_revision: Union[str, Sequence[str], None] = 'f348ffc126ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migrants', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migrants', 'role')
    # ### end Alembic commands ###
