"""deleting column

Revision ID: f348ffc126ac
Revises: 3d1162acbb6a
Create Date: 2026-05-08 20:53:03.050315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f348ffc126ac'
down_revision: Union[str, Sequence[str], None] = '3d1162acbb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migrants', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migrants', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
