"""adding otp

Revision ID: fce910841689
Revises: 4128348611b0
Create Date: 2026-06-07 08:01:54.158817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce910841689'
down_revision: Union[str, Sequence[str], None] = '4128348611b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migrants', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('migrants', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migrants', 'otp_expiry')
    op.drop_column('migrants', 'reset_otp')
    # ### end Alembic commands ###
